@hostname=localhost
@port=3000
@host=http://{{hostname}}:{{port}}

@token={{signin.response.body.$.token}}

### Auth a user
// @name signin
POST {{host}}/signin
Content-Type: application/json

{
    "nickname": "devel",
    "password": "12345678"
}

###

### Create a user with correct data
POST {{host}}/signup
Content-Type: application/json

{
    "nickname": "brunomarssinger",
    "name": "Bruno Mars",
    "email": "brunomars@gmail.com",
    "password": "12345678"
}

###

### Create a user with invalid email
POST {{host}}/signup
Content-Type: application/json

{
    "nickname": "brunomarssinger",
    "name": "Bruno Mars",
    "email": "brunomars",
    "password": "12345678"
}

###

### Create a user with invalid password
POST {{host}}/signup
Content-Type: application/json

{
    "nickname": "brunomarssinger",
    "name": "Bruno Mars",
    "email": "brunomars@gmail.com",
    "password": "1234"
}

###

### Create a user with invalid nickname
POST {{host}}/signup
Content-Type: application/json

{
    "nickname": "dev",
    "name": "Bruno Mars",
    "email": "brunomars@gmail.com",
    "password": "12345678"
}

###

### Create a user with invalid name
POST {{host}}/signup
Content-Type: application/json

{
    "nickname": "brunomarssinger",
    "name": "B",
    "email": "brunomars@gmail.com",
    "password": "12345678"
}

###

### Create note with title, content and type
POST {{host}}/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "mynote",
  "content": "mycontent",
  "type": 0
}

###

### Create note only with content and type
POST {{host}}/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "mycontent",
  "type": 0
}

###

### Create note only with title and type
POST {{host}}/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "mynote",
  "type": 0
}

###

###
{{host}}/notes
Authorization: Bearer {{token}}

###

### Create User Image
POST {{host}}/user/me/profile
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="profilePhoto"; filename="devel.jpg"
Content-Type: image/jpeg

< ./public/img/user/devel.jpg
--boundary--
###

### Update User Image
PUT {{host}}/user/me/profile
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="profilePhoto"; filename="devel.jpg"
Content-Type: image/jpeg

< ./public/img/user/devel.jpg
--boundary--
###